require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - ./lib/rubocop/cop/root_cops/avoid_ruby_prof.rb
  - ./lib/rubocop/cop/root_cops/eq_be_eql.rb
  - ./lib/rubocop/cop/root_cops/factories/factory_file_name.rb
  - ./lib/rubocop/cop/root_cops/factories/factory_name.rb
  - ./lib/rubocop/cop/root_cops/job_has_queue.rb
  - ./lib/rubocop/cop/root_cops/must_include.rb
  - ./lib/rubocop/cop/root_cops/must_inherit.rb
  - ./lib/rubocop/cop/root_cops/no_backfills_in_data_migration.rb
  - ./lib/rubocop/cop/root_cops/no_index_on_add_column.rb
  - ./lib/rubocop/cop/root_cops/no_tracers.rb
  - ./lib/rubocop/cop/root_cops/private_methods/called_private_method.rb
  - ./lib/rubocop/cop/root_cops/private_methods/called_protected.rb
  - ./lib/rubocop/cop/root_cops/private_methods/underscore_prefix.rb
  - ./lib/rubocop/cop/root_cops/raise_i18n.rb
  - ./lib/rubocop/cop/root_cops/retry_on_warning.rb
  - ./lib/rubocop/cop/root_cops/shared_context_name.rb
  - ./lib/rubocop/cop/root_cops/spec_file_name.rb
  - ./lib/rubocop/cop/root_cops/unnecessary_aggregate_failures.rb
  - ./lib/rubocop/cop/root_cops/use_before_action.rb
  - ./lib/rubocop/cop/root_cops/use_detect.rb
  - ./lib/rubocop/cop/root_cops/use_envvars.rb
  - ./lib/rubocop/cop/root_cops/use_lonely_operator.rb
  - ./lib/rubocop/cop/root_cops/up_and_down_or_change.rb
  - ./lib/rubocop/cop/root_cops/envvar_assignment.rb

AllCops:
  TargetRubyVersion: 3.0.2

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/Debugger:
  AutoCorrect: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 7

Metrics/PerceivedComplexity:
  Enabled: false

# prefixes should be avoided before predicates in general, but they make sense
# in some cases, particularly if an arg is being passed to the method
Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Rails:
  Enabled: true

# habtm should be avoided in general, but is okay in select cases
Rails/HasAndBelongsToMany:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NotToNot:
  Enabled: true
  EnforcedStyle: not_to

RSpec/NestedGroups:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

# class documentation isn't necessary
Style/Documentation:
  Enabled: false

# use !! to return a boolean where appropriate
Style/DoubleNegation:
  Enabled: false

# not going to force using guard clauses
Style/GuardClause:
  Enabled: false

Style/FloatDivision:
  Enabled: false

# continue to use string#freeze instead
Style/FrozenStringLiteralComment:
  Enabled: false

# use 1.8 style hashes
Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

# not requiring guard clauses for single-line bodies
Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6

Style/OptionalBooleanParameter:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

# use raise to raise an exception
Style/SignalException:
  EnforcedStyle: only_raise

# use double quotes for string literals
Style/StringLiterals:
  EnforcedStyle: double_quotes

# okay to use double quotes inside interpolation
Style/StringLiteralsInInterpolation:
  Enabled: false

# disabling this so that %w() syntax isn't required in nested arrays which would have mixed syntax
Style/WordArray:
  Enabled: false

# UnnecessaryAggregateFailures is off by default because it requires extra configuration within the project that uses it
RootCops/UnnecessaryAggregateFailures:
  Enabled: false

# MustInherit is off by default because it requires extra configuration within the project that uses it
# including project must configure the proper Mapping (see MustInherit class for config details)
RootCops/MustInherit:
  Enabled: false
#
# MustInclude is off by default because it requires extra configuration within the project that uses it
# including project must configure the proper Mapping (see MustInclude class for config details)
RootCops/MustInclude:
  Enabled: false

RSpec/FactoryBot/CreateList:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Layout/LineEndStringConcatenationIndentation: # (new in 1.18)
  Enabled: false

Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: false

Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true

Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: false

Lint/DuplicateBranch: # (new in 1.3)
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true

Lint/EmptyBlock: # (new in 1.1)
  Enabled: false

Lint/EmptyClass: # (new in 1.3)
  Enabled: false

Lint/EmptyInPattern: # (new in 1.16)
  Enabled: false

Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: false

Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: false

Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: false

Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: false

Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true

Lint/SymbolConversion: # (new in 1.9)
  Enabled: true

Lint/ToEnumArguments: # (new in 1.1)
  Enabled: false

Lint/TripleQuotes: # (new in 1.9)
  Enabled: true

Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: false

Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true

Naming/InclusiveLanguage: # (new in 1.18)
  Enabled: false

Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: false

Style/CollectionCompact: # (new in 1.2)
  Enabled: false

Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: false

Style/EndlessMethod: # (new in 1.8)
  Enabled: false

Style/HashConversion: # (new in 1.10)
  Enabled: true

Style/HashExcept: # (new in 1.7)
  Enabled: false

Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: true

Style/InPatternThen: # (new in 1.16)
  Enabled: false

Style/MultilineInPatternThen: # (new in 1.16)
  Enabled: false

Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: false

Style/NilLambda: # (new in 1.3)
  Enabled: false

Style/QuotedSymbols: # (new in 1.16)
  Enabled: false

Style/RedundantArgument: # (new in 1.4)
  Enabled: false

Style/StringChars: # (new in 1.12)
  Enabled: false

Style/SwapValues: # (new in 1.1)
  Enabled: false
