require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - ./lib/rubocop/cop/root_cops/avoid_ruby_prof.rb
  - ./lib/rubocop/cop/root_cops/eq_be_eql.rb
  - ./lib/rubocop/cop/root_cops/factories/factory_file_name.rb
  - ./lib/rubocop/cop/root_cops/factories/factory_name.rb
  - ./lib/rubocop/cop/root_cops/job_has_queue.rb
  - ./lib/rubocop/cop/root_cops/must_inherit.rb
  - ./lib/rubocop/cop/root_cops/no_backfills_in_data_migration.rb
  - ./lib/rubocop/cop/root_cops/no_index_on_add_column.rb
  - ./lib/rubocop/cop/root_cops/no_tracers.rb
  - ./lib/rubocop/cop/root_cops/private_methods/called_private_method.rb
  - ./lib/rubocop/cop/root_cops/private_methods/called_protected.rb
  - ./lib/rubocop/cop/root_cops/private_methods/underscore_prefix.rb
  - ./lib/rubocop/cop/root_cops/raise_i18n.rb
  - ./lib/rubocop/cop/root_cops/retry_on_warning.rb
  - ./lib/rubocop/cop/root_cops/shared_context_name.rb
  - ./lib/rubocop/cop/root_cops/spec_file_name.rb
  - ./lib/rubocop/cop/root_cops/unnecessary_aggregate_failures.rb
  - ./lib/rubocop/cop/root_cops/use_before_action.rb
  - ./lib/rubocop/cop/root_cops/use_detect.rb
  - ./lib/rubocop/cop/root_cops/use_envvars.rb
  - ./lib/rubocop/cop/root_cops/use_lonely_operator.rb
  - ./lib/rubocop/cop/root_cops/up_and_down_or_change.rb
  - ./lib/rubocop/cop/root_cops/envvar_assignment.rb

AllCops:
  TargetRubyVersion: 2.6.5

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/Debugger:
  AutoCorrect: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 7

Metrics/PerceivedComplexity:
  Enabled: false

# prefixes should be avoided before predicates in general, but they make sense
# in some cases, particularly if an arg is being passed to the method
Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Rails:
  Enabled: true

# habtm should be avoided in general, but is okay in select cases
Rails/HasAndBelongsToMany:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NotToNot:
  Enabled: true
  EnforcedStyle: not_to

RSpec/NestedGroups:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

# class documentation isn't necessary
Style/Documentation:
  Enabled: false

# use !! to return a boolean where appropriate
Style/DoubleNegation:
  Enabled: false

# not going to force using guard clauses
Style/GuardClause:
  Enabled: false

Style/FloatDivision:
  Enabled: false

# continue to use string#freeze instead
Style/FrozenStringLiteralComment:
  Enabled: false

# use 1.8 style hashes
Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

# not requiring guard clauses for single-line bodies
Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6

# use raise to raise an exception
Style/SignalException:
  EnforcedStyle: only_raise

# use double quotes for string literals
Style/StringLiterals:
  EnforcedStyle: double_quotes

# okay to use double quotes inside interpolation
Style/StringLiteralsInInterpolation:
  Enabled: false

# disabling this so that %w() syntax isn't required in nested arrays which would have mixed syntax
Style/WordArray:
  Enabled: false

# UnnecessaryAggregateFailures is off by default because it requires extra configuration within the project that uses it
RootCops/UnnecessaryAggregateFailures:
  Enabled: false

# MustInherit is off by default because it requires extra configuration within the project that uses it
# including project must configure the proper Mapping (see MustInherit class for config details)
RootCops/MustInherit:
  Enabled: false

Factories/FactoryFileName:
  Include:
    - '**/spec/factories/*.rb'

Factories/FactoryName:
  Include:
    - '**/spec/factories/*.rb'

RootCops/RetryOnWarning:
  Include:
    - '**_job.rb'