---
steps:
  - name: ":rubocop:"
    timeout_in_minutes: 5
    command: bundle exec rubocop
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: docker-compose.buildkite.yml

  - name: ":rspec:"
    timeout_in_minutes: 5
    command: bundle exec rspec .
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: docker-compose.buildkite.yml

  - name: "Ensure gem version"
    timeout_in_minutes: 5
    command: .buildkite/ensure_package_version
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: docker-compose.buildkite.yml

  - wait

  - name: ":artifactory: Publish gem"
    timeout_in_minutes: 5
    command: .buildkite/publish
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: docker-compose.buildkite.yml
        env:
          - ARTIFACTORY_PASSWORD
          - ARTIFACTORY_URL
          - ARTIFACTORY_USER
    branches:
      - master
